spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO
    com.inkfront.logisticsApplication: DEBUG

rate:
  limit:
    enabled: false

cors:
  allowed:
    origins: http://localhost:3000