package com.inkfront.logisticsApplication.util.report;

import com.inkfront.logisticsApplication.dto.response.report.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;
import java.util.Map;

@Slf4j
@Component
@RequiredArgsConstructor
public class CsvReportExporter {

    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private static final String DELIMITER = ",";
    private static final String LINE_BREAK = "\n";

    // ==================== REVENUE REPORT ====================

    public Resource exportRevenueReport(RevenueReportDTO report) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream();
             PrintWriter writer = new PrintWriter(new OutputStreamWriter(out, StandardCharsets.UTF_8))) {

            // Summary
            writer.println("Revenue Report Summary");
            writer.println("Generated on: " + report.getGeneratedAt().format(DATE_FORMAT));
            writer.println("Period: " + report.getSummary().getStartDate() + " to " + report.getSummary().getEndDate());
            writer.println("Generated by: " + report.getSummary().getGeneratedBy());
            writer.println();

            // Revenue by Day
            writer.println("Revenue by Day");
            writer.println("Date" + DELIMITER + "Revenue");
            report.getRevenueByDay().forEach((date, amount) ->
                    writer.println(date.format(DATE_FORMAT) + DELIMITER + amount)
            );
            writer.println();

            // Revenue by Week
            writer.println("Revenue by Week");
            writer.println("Week" + DELIMITER + "Revenue");
            report.getRevenueByWeek().forEach((week, amount) ->
                    writer.println(escapeCsv(week) + DELIMITER + amount)
            );
            writer.println();

            // Revenue by Month
            writer.println("Revenue by Month");
            writer.println("Month" + DELIMITER + "Revenue");
            report.getRevenueByMonth().forEach((month, amount) ->
                    writer.println(escapeCsv(month) + DELIMITER + amount)
            );
            writer.println();

            // Statistics
            writer.println("Statistics");
            writer.println("Total Revenue" + DELIMITER + report.getTotalRevenue());
            writer.println("Average Order Value" + DELIMITER + report.getAverageOrderValue());
            writer.println("Revenue Growth (%)" + DELIMITER + report.getRevenueGrowth());
            writer.println("Pending Revenue" + DELIMITER + report.getPendingRevenue());
            writer.println("Cancelled Revenue" + DELIMITER + report.getCancelledRevenue());

            writer.flush();
            return new ByteArrayResource(out.toByteArray());
        } catch (Exception e) {
            log.error("Error generating CSV revenue report", e);
            throw new RuntimeException("CSV generation failed", e);
        }
    }

    // ==================== ORDER REPORT ====================

    public Resource exportOrderReport(OrderReportDTO report) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream();
             PrintWriter writer = new PrintWriter(new OutputStreamWriter(out, StandardCharsets.UTF_8))) {

            // Summary
            writer.println("Order Report Summary");
            writer.println("Generated on: " + report.getGeneratedAt().format(DATE_FORMAT));
            writer.println("Period: " + report.getSummary().getStartDate() + " to " + report.getSummary().getEndDate());
            writer.println("Generated by: " + report.getSummary().getGeneratedBy());
            writer.println();

            // Statistics
            writer.println("Statistics");
            writer.println("Total Orders" + DELIMITER + report.getTotalOrders());
            writer.println("Completed" + DELIMITER + report.getCompletedOrders());
            writer.println("Cancelled" + DELIMITER + report.getCancelledOrders());
            writer.println("In Transit" + DELIMITER + report.getInTransitOrders());
            writer.println("Average Delivery Time (min)" + DELIMITER + report.getAverageDeliveryTimeMinutes());
            writer.println("Average Distance (km)" + DELIMITER + report.getAverageDistanceKm());
            writer.println("Most Requested Vehicle" + DELIMITER + escapeCsv(report.getMostRequestedVehicle()));
            writer.println();

            // Orders by Status
            writer.println("Orders by Status");
            writer.println("Status" + DELIMITER + "Count");
            report.getOrdersByStatus().forEach((status, count) ->
                    writer.println(escapeCsv(status) + DELIMITER + count)
            );
            writer.println();

            // Orders by Location
            writer.println("Orders by Location");
            writer.println("Location" + DELIMITER + "Count");
            report.getOrdersByLocation().forEach((location, count) ->
                    writer.println(escapeCsv(location) + DELIMITER + count)
            );
            writer.println();

            // Peak Order Hours
            writer.println("Peak Order Hours");
            writer.println("Hour" + DELIMITER + "Orders");
            report.getPeakOrderHours().forEach((hour, count) ->
                    writer.println(hour + DELIMITER + count)
            );

            writer.flush();
            return new ByteArrayResource(out.toByteArray());
        } catch (Exception e) {
            log.error("Error generating CSV order report", e);
            throw new RuntimeException("CSV generation failed", e);
        }
    }

    // ==================== DRIVER REPORT ====================

    public Resource exportDriverReport(DriverReportDTO report) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream();
             PrintWriter writer = new PrintWriter(new OutputStreamWriter(out, StandardCharsets.UTF_8))) {

            // Summary
            writer.println("Driver Report Summary");
            writer.println("Generated on: " + report.getGeneratedAt().format(DATE_FORMAT));
            writer.println("Period: " + report.getSummary().getStartDate() + " to " + report.getSummary().getEndDate());
            writer.println("Generated by: " + report.getSummary().getGeneratedBy());
            writer.println();

            // Statistics
            writer.println("Statistics");
            writer.println("Total Drivers" + DELIMITER + report.getTotalDrivers());
            writer.println("Available" + DELIMITER + report.getAvailableDrivers());
            writer.println("Busy" + DELIMITER + report.getBusyDrivers());
            writer.println("Completed Deliveries" + DELIMITER + report.getCompletedDeliveries());
            writer.println("Average Rating" + DELIMITER + report.getAverageRating());
            writer.println("Total Distance Covered (km)" + DELIMITER + report.getTotalDistanceCoveredKm());
            writer.println("Revenue Generated" + DELIMITER + report.getRevenueGenerated());
            writer.println();

            // Driver Performance
            writer.println("Driver Performance (Deliveries)");
            writer.println("Driver ID" + DELIMITER + "Deliveries");
            report.getDriverPerformance().forEach((driverId, deliveries) ->
                    writer.println(escapeCsv(driverId) + DELIMITER + deliveries)
            );

            writer.flush();
            return new ByteArrayResource(out.toByteArray());
        } catch (Exception e) {
            log.error("Error generating CSV driver report", e);
            throw new RuntimeException("CSV generation failed", e);
        }
    }

    // ==================== CUSTOMER REPORT ====================

    public Resource exportCustomerReport(CustomerReportDTO report) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream();
             PrintWriter writer = new PrintWriter(new OutputStreamWriter(out, StandardCharsets.UTF_8))) {

            // Summary
            writer.println("Customer Report Summary");
            writer.println("Generated on: " + report.getGeneratedAt().format(DATE_FORMAT));
            writer.println("Period: " + report.getSummary().getStartDate() + " to " + report.getSummary().getEndDate());
            writer.println("Generated by: " + report.getSummary().getGeneratedBy());
            writer.println();

            // Statistics
            writer.println("Statistics");
            writer.println("Total Customers" + DELIMITER + report.getTotalCustomers());
            writer.println("New Customers" + DELIMITER + report.getNewCustomers());
            writer.println("Returning Customers" + DELIMITER + report.getReturningCustomers());
            writer.println("Average Spend" + DELIMITER + report.getAverageSpend());
            writer.println("Completed Orders" + DELIMITER + report.getCompletedOrders());
            writer.println("Cancelled Orders" + DELIMITER + report.getCancelledOrders());
            writer.println();

            // Top Customers
            writer.println("Top Customers");
            for (String customer : report.getTopCustomers()) {
                writer.println(escapeCsv(customer));
            }
            writer.println();

            // Most Active Customers
            writer.println("Most Active Customers");
            for (String customer : report.getMostActiveCustomers()) {
                writer.println(escapeCsv(customer));
            }

            writer.flush();
            return new ByteArrayResource(out.toByteArray());
        } catch (Exception e) {
            log.error("Error generating CSV customer report", e);
            throw new RuntimeException("CSV generation failed", e);
        }
    }

    // ==================== HELPER METHODS ====================

    /**
     * Escapes CSV values if they contain delimiter, quotes, or line breaks.
     */
    private String escapeCsv(String value) {
        if (value == null) return "";
        if (value.contains(DELIMITER) || value.contains("\"") || value.contains(LINE_BREAK)) {
            return "\"" + value.replace("\"", "\"\"") + "\"";
        }
        return value;
    }
}